doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'

    # IMPORTANT: You MUST configure your server version,
    server_version: mariadb-10.3.11

    # needed for MySQL
    charset: utf8mb4
    default_table_options:
      collate: utf8mb4_unicode_ci

    types:
      json: Doctrine\DBAL\Types\JsonType

    # backtrace queries in profiler (increases memory usage per request)
    #profiling_collect_backtrace: '%kernel.debug%'

  orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
    dql:
      numeric_functions:
        time_diff: App\DQL\TimeDiff
        time_add: App\DQL\TimeAdd
        time_sub: App\DQL\TimeSub
      string_functions:
        match: DoctrineExtensions\Query\Mysql\MatchAgainst
        rand: DoctrineExtensions\Query\Mysql\Rand
